// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct BetTokenClientProgram;
impl sails_rs::client::Program for BetTokenClientProgram {}
pub trait BetTokenClient {
    type Env: sails_rs::client::GearEnv;
    fn bet_token(&self) -> sails_rs::client::Service<bet_token::BetTokenImpl, Self::Env>;
    fn access_control(
        &self,
    ) -> sails_rs::client::Service<access_control::AccessControlImpl, Self::Env>;
    fn vft_admin(&self) -> sails_rs::client::Service<vft_admin::VftAdminImpl, Self::Env>;
    fn metadata(&self) -> sails_rs::client::Service<metadata::MetadataImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> BetTokenClient
    for sails_rs::client::Actor<BetTokenClientProgram, E>
{
    type Env = E;
    fn bet_token(&self) -> sails_rs::client::Service<bet_token::BetTokenImpl, Self::Env> {
        self.service(stringify!(BetToken))
    }
    fn access_control(
        &self,
    ) -> sails_rs::client::Service<access_control::AccessControlImpl, Self::Env> {
        self.service(stringify!(AccessControl))
    }
    fn vft_admin(&self) -> sails_rs::client::Service<vft_admin::VftAdminImpl, Self::Env> {
        self.service(stringify!(VftAdmin))
    }
    fn metadata(&self) -> sails_rs::client::Service<metadata::MetadataImpl, Self::Env> {
        self.service(stringify!(Metadata))
    }
}
pub trait BetTokenClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        admin: ActorId,
        name: String,
        symbol: String,
        decimals: u8,
        claim_config: Option<ClaimConfig>,
    ) -> sails_rs::client::PendingCtor<BetTokenClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> BetTokenClientCtors
    for sails_rs::client::Deployment<BetTokenClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        admin: ActorId,
        name: String,
        symbol: String,
        decimals: u8,
        claim_config: Option<ClaimConfig>,
    ) -> sails_rs::client::PendingCtor<BetTokenClientProgram, io::Create, Self::Env> {
        self.pending_ctor((admin, name, symbol, decimals, claim_config))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (admin: ActorId, name: String, symbol: String, decimals: u8, claim_config: Option<super::ClaimConfig>) -> ());
}

pub mod bet_token {
    use super::*;
    pub trait BetToken {
        type Env: sails_rs::client::GearEnv;
        fn add_admin(
            &mut self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env>;
        fn admin_mint(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::AdminMint, Self::Env>;
        fn allow_spender(
            &mut self,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::AllowSpender, Self::Env>;
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env>;
        fn claim(&mut self) -> sails_rs::client::PendingCall<io::Claim, Self::Env>;
        fn disallow_spender(
            &mut self,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::DisallowSpender, Self::Env>;
        fn grant_role(
            &mut self,
            role_id: [u8; 32],
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRole, Self::Env>;
        fn import_balances(
            &mut self,
            balances: Vec<ImportedBalance>,
        ) -> sails_rs::client::PendingCall<io::ImportBalances, Self::Env>;
        fn import_claim_states(
            &mut self,
            claim_states: Vec<ImportedClaimState>,
        ) -> sails_rs::client::PendingCall<io::ImportClaimStates, Self::Env>;
        fn pause_claim(&mut self) -> sails_rs::client::PendingCall<io::PauseClaim, Self::Env>;
        fn resume_claim(&mut self) -> sails_rs::client::PendingCall<io::ResumeClaim, Self::Env>;
        fn revoke_role(
            &mut self,
            role_id: [u8; 32],
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRole, Self::Env>;
        fn set_claim_config(
            &mut self,
            config: ClaimConfig,
        ) -> sails_rs::client::PendingCall<io::SetClaimConfig, Self::Env>;
        fn set_claim_day_start_offset(
            &mut self,
            day_start_offset_ms: u64,
        ) -> sails_rs::client::PendingCall<io::SetClaimDayStartOffset, Self::Env>;
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env>;
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env>;
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env>;
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env>;
        fn get_claim_config(&self) -> sails_rs::client::PendingCall<io::GetClaimConfig, Self::Env>;
        fn get_claim_preview(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetClaimPreview, Self::Env>;
        fn get_claim_state(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetClaimState, Self::Env>;
        fn get_claim_state_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetClaimStateCount, Self::Env>;
        fn is_claim_paused(&self) -> sails_rs::client::PendingCall<io::IsClaimPaused, Self::Env>;
        fn is_spender_allowed(
            &self,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsSpenderAllowed, Self::Env>;
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env>;
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env>;
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env>;
    }
    pub struct BetTokenImpl;
    impl<E: sails_rs::client::GearEnv> BetToken for sails_rs::client::Service<BetTokenImpl, E> {
        type Env = E;
        fn add_admin(
            &mut self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env> {
            self.pending_call((account,))
        }
        fn admin_mint(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::AdminMint, Self::Env> {
            self.pending_call((to, value))
        }
        fn allow_spender(
            &mut self,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::AllowSpender, Self::Env> {
            self.pending_call((spender,))
        }
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env> {
            self.pending_call((spender, value))
        }
        fn claim(&mut self) -> sails_rs::client::PendingCall<io::Claim, Self::Env> {
            self.pending_call(())
        }
        fn disallow_spender(
            &mut self,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::DisallowSpender, Self::Env> {
            self.pending_call((spender,))
        }
        fn grant_role(
            &mut self,
            role_id: [u8; 32],
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRole, Self::Env> {
            self.pending_call((role_id, account))
        }
        fn import_balances(
            &mut self,
            balances: Vec<ImportedBalance>,
        ) -> sails_rs::client::PendingCall<io::ImportBalances, Self::Env> {
            self.pending_call((balances,))
        }
        fn import_claim_states(
            &mut self,
            claim_states: Vec<ImportedClaimState>,
        ) -> sails_rs::client::PendingCall<io::ImportClaimStates, Self::Env> {
            self.pending_call((claim_states,))
        }
        fn pause_claim(&mut self) -> sails_rs::client::PendingCall<io::PauseClaim, Self::Env> {
            self.pending_call(())
        }
        fn resume_claim(&mut self) -> sails_rs::client::PendingCall<io::ResumeClaim, Self::Env> {
            self.pending_call(())
        }
        fn revoke_role(
            &mut self,
            role_id: [u8; 32],
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRole, Self::Env> {
            self.pending_call((role_id, account))
        }
        fn set_claim_config(
            &mut self,
            config: ClaimConfig,
        ) -> sails_rs::client::PendingCall<io::SetClaimConfig, Self::Env> {
            self.pending_call((config,))
        }
        fn set_claim_day_start_offset(
            &mut self,
            day_start_offset_ms: u64,
        ) -> sails_rs::client::PendingCall<io::SetClaimDayStartOffset, Self::Env> {
            self.pending_call((day_start_offset_ms,))
        }
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env> {
            self.pending_call((to, value))
        }
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env> {
            self.pending_call((from, to, value))
        }
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env> {
            self.pending_call((owner, spender))
        }
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((account,))
        }
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env> {
            self.pending_call(())
        }
        fn get_claim_config(&self) -> sails_rs::client::PendingCall<io::GetClaimConfig, Self::Env> {
            self.pending_call(())
        }
        fn get_claim_preview(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetClaimPreview, Self::Env> {
            self.pending_call((user,))
        }
        fn get_claim_state(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetClaimState, Self::Env> {
            self.pending_call((user,))
        }
        fn get_claim_state_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetClaimStateCount, Self::Env> {
            self.pending_call(())
        }
        fn is_claim_paused(&self) -> sails_rs::client::PendingCall<io::IsClaimPaused, Self::Env> {
            self.pending_call(())
        }
        fn is_spender_allowed(
            &self,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsSpenderAllowed, Self::Env> {
            self.pending_call((spender,))
        }
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env> {
            self.pending_call(())
        }
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env> {
            self.pending_call(())
        }
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddAdmin (account: ActorId) -> ());
        sails_rs::io_struct_impl!(AdminMint (to: ActorId, value: U256) -> ());
        sails_rs::io_struct_impl!(AllowSpender (spender: ActorId) -> ());
        sails_rs::io_struct_impl!(Approve (spender: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(Claim () -> super::ClaimState);
        sails_rs::io_struct_impl!(DisallowSpender (spender: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantRole (role_id: [u8; 32], account: ActorId) -> ());
        sails_rs::io_struct_impl!(ImportBalances (balances: Vec<super::ImportedBalance>) -> u32);
        sails_rs::io_struct_impl!(ImportClaimStates (claim_states: Vec<super::ImportedClaimState>) -> u32);
        sails_rs::io_struct_impl!(PauseClaim () -> ());
        sails_rs::io_struct_impl!(ResumeClaim () -> ());
        sails_rs::io_struct_impl!(RevokeRole (role_id: [u8; 32], account: ActorId) -> ());
        sails_rs::io_struct_impl!(SetClaimConfig (config: super::ClaimConfig) -> ());
        sails_rs::io_struct_impl!(SetClaimDayStartOffset (day_start_offset_ms: u64) -> ());
        sails_rs::io_struct_impl!(Transfer (to: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(TransferFrom (from: ActorId, to: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(Allowance (owner: ActorId, spender: ActorId) -> U256);
        sails_rs::io_struct_impl!(BalanceOf (account: ActorId) -> U256);
        sails_rs::io_struct_impl!(Decimals () -> u8);
        sails_rs::io_struct_impl!(GetClaimConfig () -> super::ClaimConfig);
        sails_rs::io_struct_impl!(GetClaimPreview (user: ActorId) -> super::ClaimPreview);
        sails_rs::io_struct_impl!(GetClaimState (user: ActorId) -> super::ClaimState);
        sails_rs::io_struct_impl!(GetClaimStateCount () -> u64);
        sails_rs::io_struct_impl!(IsClaimPaused () -> bool);
        sails_rs::io_struct_impl!(IsSpenderAllowed (spender: ActorId) -> bool);
        sails_rs::io_struct_impl!(Name () -> String);
        sails_rs::io_struct_impl!(Symbol () -> String);
        sails_rs::io_struct_impl!(TotalSupply () -> U256);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum BetTokenEvents {
            Approved {
                owner: ActorId,
                spender: ActorId,
                value: U256,
                changed: bool,
            },
            Claimed {
                user: ActorId,
                amount: U256,
                streak_days: u32,
                claimed_at: u64,
            },
            StreakUpdated {
                user: ActorId,
                streak_days: u32,
                reset: bool,
            },
            ClaimConfigUpdated(ClaimConfig),
            ClaimPaused,
            ClaimResumed,
            SpenderAllowed(ActorId),
            SpenderDisallowed(ActorId),
            MigrationBalancesImported {
                count: u32,
            },
            MigrationClaimStatesImported {
                count: u32,
            },
        }
        impl sails_rs::client::Event for BetTokenEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "Approved",
                "Claimed",
                "StreakUpdated",
                "ClaimConfigUpdated",
                "ClaimPaused",
                "ClaimResumed",
                "SpenderAllowed",
                "SpenderDisallowed",
                "MigrationBalancesImported",
                "MigrationClaimStatesImported",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for BetTokenImpl {
            type Event = BetTokenEvents;
        }
    }
}

pub mod access_control {
    use super::*;
    pub trait AccessControl {
        type Env: sails_rs::client::GearEnv;
        /// Grants `role_id` to `target_account`.
        ///
        /// If `target_account` had not been already granted `role_id`, emits a `RoleGranted`
        /// event.
        ///
        /// # Requirements
        ///
        /// * The caller must have `role_id`'s admin role.
        fn grant_role(
            &mut self,
            role_id: [u8; 32],
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRole, Self::Env>;
        /// Grants `role_ids` to `target_account`.
        ///
        /// If `target_account` had not been already granted any of the `role_ids`,
        /// emits a `RoleGranted` event for each newly granted role.
        ///
        /// # Requirements
        ///
        /// * The caller must have the admin role for all specified `role_ids`.
        fn grant_roles_batch(
            &mut self,
            role_ids: Vec<[u8; 32]>,
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRolesBatch, Self::Env>;
        /// Revokes `role_id` from the calling account.
        ///
        /// Roles are often managed via `grant_role` and `revoke_role`: this function's
        /// purpose is to provide a mechanism for accounts to lose their privileges
        /// if they are compromised (such as when a trusted device is misplaced).
        ///
        /// If the calling account had been granted `role_id`, emits a `RoleRevoked`
        /// event.
        ///
        /// # Requirements
        ///
        /// * The caller must be `account_id`.
        fn renounce_role(
            &mut self,
            role_id: [u8; 32],
            account_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::RenounceRole, Self::Env>;
        /// Revokes `role_id` from `target_account`.
        ///
        /// If `target_account` had been granted `role_id`, emits a `RoleRevoked` event.
        ///
        /// # Requirements
        ///
        /// * The caller must have `role_id`'s admin role.
        fn revoke_role(
            &mut self,
            role_id: [u8; 32],
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRole, Self::Env>;
        /// Revokes `role_ids` from `target_account`.
        ///
        /// If `target_account` had been granted any of the `role_ids`,
        /// emits a `RoleRevoked` event for each newly revoked role.
        ///
        /// # Requirements
        ///
        /// * The caller must have the admin role for all specified `role_ids`.
        fn revoke_roles_batch(
            &mut self,
            role_ids: Vec<[u8; 32]>,
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRolesBatch, Self::Env>;
        /// Sets `new_admin_role_id` as the admin role for `role_id`.
        ///
        /// Emits a `RoleAdminChanged` event.
        ///
        /// # Requirements
        ///
        /// * The caller must have `role_id`'s admin role.
        fn set_role_admin(
            &mut self,
            role_id: [u8; 32],
            new_admin_role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::SetRoleAdmin, Self::Env>;
        /// Returns the number of roles assigned to the specified member.
        ///
        /// # Arguments
        ///
        /// * `member_id` - The account identifier.
        fn get_member_role_count(
            &self,
            member_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetMemberRoleCount, Self::Env>;
        /// Returns a list of roles assigned to the specified member with pagination.
        ///
        /// # Arguments
        ///
        /// * `member_id` - The account identifier.
        /// * `query` - Optional pagination configuration.
        fn get_member_roles(
            &self,
            member_id: ActorId,
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetMemberRoles, Self::Env>;
        /// Returns the admin role ID that controls `role_id`.
        ///
        /// # Arguments
        ///
        /// * `role_id` - The role identifier.
        ///
        /// # Returns
        ///
        /// The `RoleId` of the administrator.
        fn get_role_admin(
            &self,
            role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::GetRoleAdmin, Self::Env>;
        /// Returns the total number of roles in the system.
        fn get_role_count(&self) -> sails_rs::client::PendingCall<io::GetRoleCount, Self::Env>;
        /// Returns the number of members in the specified role.
        ///
        /// # Arguments
        ///
        /// * `role_id` - The role identifier.
        fn get_role_member_count(
            &self,
            role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::GetRoleMemberCount, Self::Env>;
        /// Returns a list of members in the specified role with pagination.
        ///
        /// # Arguments
        ///
        /// * `role_id` - The role identifier.
        /// * `query` - Optional pagination configuration.
        fn get_role_members(
            &self,
            role_id: [u8; 32],
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetRoleMembers, Self::Env>;
        /// Returns a list of role IDs with pagination.
        ///
        /// # Arguments
        ///
        /// * `query` - Optional pagination configuration.
        fn get_roles(
            &self,
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetRoles, Self::Env>;
        /// Checks if `account_id` has been granted `role_id`.
        ///
        /// # Arguments
        ///
        /// * `role_id` - The role identifier.
        /// * `account_id` - The account identifier.
        ///
        /// # Returns
        ///
        /// `true` if the account possesses the role.
        fn has_role(
            &self,
            role_id: [u8; 32],
            account_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::HasRole, Self::Env>;
    }
    pub struct AccessControlImpl;
    impl<E: sails_rs::client::GearEnv> AccessControl
        for sails_rs::client::Service<AccessControlImpl, E>
    {
        type Env = E;
        fn grant_role(
            &mut self,
            role_id: [u8; 32],
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRole, Self::Env> {
            self.pending_call((role_id, target_account))
        }
        fn grant_roles_batch(
            &mut self,
            role_ids: Vec<[u8; 32]>,
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRolesBatch, Self::Env> {
            self.pending_call((role_ids, target_account))
        }
        fn renounce_role(
            &mut self,
            role_id: [u8; 32],
            account_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::RenounceRole, Self::Env> {
            self.pending_call((role_id, account_id))
        }
        fn revoke_role(
            &mut self,
            role_id: [u8; 32],
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRole, Self::Env> {
            self.pending_call((role_id, target_account))
        }
        fn revoke_roles_batch(
            &mut self,
            role_ids: Vec<[u8; 32]>,
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRolesBatch, Self::Env> {
            self.pending_call((role_ids, target_account))
        }
        fn set_role_admin(
            &mut self,
            role_id: [u8; 32],
            new_admin_role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::SetRoleAdmin, Self::Env> {
            self.pending_call((role_id, new_admin_role_id))
        }
        fn get_member_role_count(
            &self,
            member_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetMemberRoleCount, Self::Env> {
            self.pending_call((member_id,))
        }
        fn get_member_roles(
            &self,
            member_id: ActorId,
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetMemberRoles, Self::Env> {
            self.pending_call((member_id, query))
        }
        fn get_role_admin(
            &self,
            role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::GetRoleAdmin, Self::Env> {
            self.pending_call((role_id,))
        }
        fn get_role_count(&self) -> sails_rs::client::PendingCall<io::GetRoleCount, Self::Env> {
            self.pending_call(())
        }
        fn get_role_member_count(
            &self,
            role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::GetRoleMemberCount, Self::Env> {
            self.pending_call((role_id,))
        }
        fn get_role_members(
            &self,
            role_id: [u8; 32],
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetRoleMembers, Self::Env> {
            self.pending_call((role_id, query))
        }
        fn get_roles(
            &self,
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetRoles, Self::Env> {
            self.pending_call((query,))
        }
        fn has_role(
            &self,
            role_id: [u8; 32],
            account_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::HasRole, Self::Env> {
            self.pending_call((role_id, account_id))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(GrantRole (role_id: [u8; 32], target_account: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantRolesBatch (role_ids: Vec<[u8; 32]>, target_account: ActorId) -> ());
        sails_rs::io_struct_impl!(RenounceRole (role_id: [u8; 32], account_id: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeRole (role_id: [u8; 32], target_account: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeRolesBatch (role_ids: Vec<[u8; 32]>, target_account: ActorId) -> ());
        sails_rs::io_struct_impl!(SetRoleAdmin (role_id: [u8; 32], new_admin_role_id: [u8; 32]) -> ());
        sails_rs::io_struct_impl!(GetMemberRoleCount (member_id: ActorId) -> u32);
        sails_rs::io_struct_impl!(GetMemberRoles (member_id: ActorId, query: Option<super::Pagination>) -> Vec<[u8; 32]>);
        sails_rs::io_struct_impl!(GetRoleAdmin (role_id: [u8; 32]) -> [u8; 32]);
        sails_rs::io_struct_impl!(GetRoleCount () -> u32);
        sails_rs::io_struct_impl!(GetRoleMemberCount (role_id: [u8; 32]) -> u32);
        sails_rs::io_struct_impl!(GetRoleMembers (role_id: [u8; 32], query: Option<super::Pagination>) -> Vec<ActorId>);
        sails_rs::io_struct_impl!(GetRoles (query: Option<super::Pagination>) -> Vec<[u8; 32]>);
        sails_rs::io_struct_impl!(HasRole (role_id: [u8; 32], account_id: ActorId) -> bool);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum AccessControlEvents {
            /// Emitted when `target_account` is granted `role_id`.
            RoleGranted {
                role_id: [u8; 32],
                target_account: ActorId,
                sender: ActorId,
            },
            /// Emitted when `role_id` is revoked from `target_account`.
            RoleRevoked {
                role_id: [u8; 32],
                target_account: ActorId,
                sender: ActorId,
            },
            /// Emitted when `new_admin_role_id` is set as the admin role for `role_id`.
            RoleAdminChanged {
                role_id: [u8; 32],
                previous_admin_role_id: [u8; 32],
                new_admin_role_id: [u8; 32],
                sender: ActorId,
            },
        }
        impl sails_rs::client::Event for AccessControlEvents {
            const EVENT_NAMES: &'static [Route] =
                &["RoleGranted", "RoleRevoked", "RoleAdminChanged"];
        }
        impl sails_rs::client::ServiceWithEvents for AccessControlImpl {
            type Event = AccessControlEvents;
        }
    }
}

pub mod vft_admin {
    use super::*;
    pub trait VftAdmin {
        type Env: sails_rs::client::GearEnv;
        /// Appends a new shard to the allowances storage map.
        ///
        /// # Requirements
        /// * Caller must have `DEFAULT_ADMIN_ROLE`.
        ///
        /// # Arguments
        /// * `capacity` - The capacity of the new shard.
        fn append_allowances_shard(
            &mut self,
            capacity: u32,
        ) -> sails_rs::client::PendingCall<io::AppendAllowancesShard, Self::Env>;
        /// Appends a new shard to the balances storage map.
        ///
        /// # Requirements
        /// * Caller must have `DEFAULT_ADMIN_ROLE`.
        ///
        /// # Arguments
        /// * `capacity` - The capacity of the new shard.
        fn append_balances_shard(
            &mut self,
            capacity: u32,
        ) -> sails_rs::client::PendingCall<io::AppendBalancesShard, Self::Env>;
        /// Approves `spender` to spend `value` from `owner`'s account.
        ///
        /// This is an admin function allowing the admin to set approvals arbitrarily.
        ///
        /// # Requirements
        /// * Caller must have `DEFAULT_ADMIN_ROLE`.
        ///
        /// # Arguments
        /// * `owner` - The account owning the tokens.
        /// * `spender` - The account to be approved.
        /// * `value` - The amount to approve.
        fn approve_from(
            &mut self,
            owner: ActorId,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::ApproveFrom, Self::Env>;
        /// Burns `value` tokens from `from` account.
        ///
        /// # Requirements
        /// * Caller must have `BURNER_ROLE`.
        ///
        /// # Arguments
        /// * `from` - The account to burn tokens from.
        /// * `value` - The amount to burn.
        fn burn(
            &mut self,
            from: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env>;
        /// Terminates the program and sends value to `inheritor`.
        ///
        /// # Requirements
        /// * Caller must have `DEFAULT_ADMIN_ROLE`.
        /// * Program must be paused.
        fn exit(
            &mut self,
            inheritor: ActorId,
        ) -> sails_rs::client::PendingCall<io::Exit, Self::Env>;
        /// Mints `value` tokens to `to` account.
        ///
        /// # Requirements
        /// * Caller must have `MINTER_ROLE`.
        ///
        /// # Arguments
        /// * `to` - The recipient of the minted tokens.
        /// * `value` - The amount to mint.
        fn mint(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env>;
        /// Pauses the contract.
        ///
        /// # Requirements
        /// * Caller must have `PAUSER_ROLE`.
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        /// Resumes the contract.
        ///
        /// # Requirements
        /// * Caller must have `PAUSER_ROLE`.
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env>;
        /// Sets the expiry period for allowances.
        ///
        /// # Requirements
        /// * Caller must have `DEFAULT_ADMIN_ROLE`.
        ///
        /// # Arguments
        /// * `period` - The new expiry period in blocks.
        fn set_expiry_period(
            &mut self,
            period: u32,
        ) -> sails_rs::client::PendingCall<io::SetExpiryPeriod, Self::Env>;
        /// Returns `true` if the contract is paused.
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env>;
    }
    pub struct VftAdminImpl;
    impl<E: sails_rs::client::GearEnv> VftAdmin for sails_rs::client::Service<VftAdminImpl, E> {
        type Env = E;
        fn append_allowances_shard(
            &mut self,
            capacity: u32,
        ) -> sails_rs::client::PendingCall<io::AppendAllowancesShard, Self::Env> {
            self.pending_call((capacity,))
        }
        fn append_balances_shard(
            &mut self,
            capacity: u32,
        ) -> sails_rs::client::PendingCall<io::AppendBalancesShard, Self::Env> {
            self.pending_call((capacity,))
        }
        fn approve_from(
            &mut self,
            owner: ActorId,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::ApproveFrom, Self::Env> {
            self.pending_call((owner, spender, value))
        }
        fn burn(
            &mut self,
            from: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env> {
            self.pending_call((from, value))
        }
        fn exit(
            &mut self,
            inheritor: ActorId,
        ) -> sails_rs::client::PendingCall<io::Exit, Self::Env> {
            self.pending_call((inheritor,))
        }
        fn mint(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env> {
            self.pending_call((to, value))
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env> {
            self.pending_call(())
        }
        fn set_expiry_period(
            &mut self,
            period: u32,
        ) -> sails_rs::client::PendingCall<io::SetExpiryPeriod, Self::Env> {
            self.pending_call((period,))
        }
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AppendAllowancesShard (capacity: u32) -> ());
        sails_rs::io_struct_impl!(AppendBalancesShard (capacity: u32) -> ());
        sails_rs::io_struct_impl!(ApproveFrom (owner: ActorId, spender: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(Burn (from: ActorId, value: U256) -> ());
        sails_rs::io_struct_impl!(Exit (inheritor: ActorId) -> ());
        sails_rs::io_struct_impl!(Mint (to: ActorId, value: U256) -> ());
        sails_rs::io_struct_impl!(Pause () -> ());
        sails_rs::io_struct_impl!(Resume () -> ());
        sails_rs::io_struct_impl!(SetExpiryPeriod (period: u32) -> ());
        sails_rs::io_struct_impl!(IsPaused () -> bool);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum VftAdminEvents {
            BurnerTookPlace,
            MinterTookPlace,
            /// Emitted when the allowance expiry period is changed.
            ExpiryPeriodChanged(u32),
            /// Emitted when the program exits.
            Exited(ActorId),
            Paused,
            Resumed,
        }
        impl sails_rs::client::Event for VftAdminEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "BurnerTookPlace",
                "MinterTookPlace",
                "ExpiryPeriodChanged",
                "Exited",
                "Paused",
                "Resumed",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for VftAdminImpl {
            type Event = VftAdminEvents;
        }
    }
}

pub mod metadata {
    use super::*;
    pub trait Metadata {
        type Env: sails_rs::client::GearEnv;
        /// Returns the number of decimals used by the VFT.
        ///
        /// # Returns
        ///
        /// The decimals as a `u8`.
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env>;
        /// Returns the name of the VFT.
        ///
        /// # Returns
        ///
        /// The name as a `String`.
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env>;
        /// Returns the symbol of the VFT.
        ///
        /// # Returns
        ///
        /// The symbol as a `String`.
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env>;
    }
    pub struct MetadataImpl;
    impl<E: sails_rs::client::GearEnv> Metadata for sails_rs::client::Service<MetadataImpl, E> {
        type Env = E;
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env> {
            self.pending_call(())
        }
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env> {
            self.pending_call(())
        }
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Decimals () -> u8);
        sails_rs::io_struct_impl!(Name () -> String);
        sails_rs::io_struct_impl!(Symbol () -> String);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ClaimConfig {
    pub base_claim_amount: U256,
    pub max_claim_amount: U256,
    pub streak_step: U256,
    pub streak_cap_days: u32,
    pub claim_period: u64,
    pub day_start_offset_ms: u64,
    pub claim_paused: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ClaimState {
    pub last_claim_at: Option<u64>,
    pub streak_days: u32,
    pub total_claimed: U256,
    pub claim_count: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ImportedBalance {
    pub user: ActorId,
    pub balance: U256,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ImportedClaimState {
    pub user: ActorId,
    pub state: ClaimState,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ClaimPreview {
    pub amount: U256,
    pub streak_days: u32,
    pub next_claim_at: Option<u64>,
    pub can_claim_now: bool,
}
/// Pagination parameters for listing roles or members.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Pagination {
    /// The number of items to skip.
    pub offset: u32,
    /// The maximum number of items to return.
    pub limit: u32,
}
