// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct BetLaneClientProgram;
impl sails_rs::client::Program for BetLaneClientProgram {}
pub trait BetLaneClient {
    type Env: sails_rs::client::GearEnv;
    fn bet_lane(&self) -> sails_rs::client::Service<bet_lane::BetLaneImpl, Self::Env>;
    fn access_control(
        &self,
    ) -> sails_rs::client::Service<access_control::AccessControlImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> BetLaneClient
    for sails_rs::client::Actor<BetLaneClientProgram, E>
{
    type Env = E;
    fn bet_lane(&self) -> sails_rs::client::Service<bet_lane::BetLaneImpl, Self::Env> {
        self.service(stringify!(BetLane))
    }
    fn access_control(
        &self,
    ) -> sails_rs::client::Service<access_control::AccessControlImpl, Self::Env> {
        self.service(stringify!(AccessControl))
    }
}
pub trait BetLaneClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        admin: ActorId,
        basket_program_id: ActorId,
        bet_token_id: ActorId,
        config: Option<BetLaneConfig>,
    ) -> sails_rs::client::PendingCtor<BetLaneClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> BetLaneClientCtors
    for sails_rs::client::Deployment<BetLaneClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        admin: ActorId,
        basket_program_id: ActorId,
        bet_token_id: ActorId,
        config: Option<BetLaneConfig>,
    ) -> sails_rs::client::PendingCtor<BetLaneClientProgram, io::Create, Self::Env> {
        self.pending_ctor((admin, basket_program_id, bet_token_id, config))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (admin: ActorId, basket_program_id: ActorId, bet_token_id: ActorId, config: Option<super::BetLaneConfig>) -> ());
}

pub mod bet_lane {
    use super::*;
    pub trait BetLane {
        type Env: sails_rs::client::GearEnv;
        fn add_admin(
            &mut self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env>;
        fn claim(&mut self, basket_id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env>;
        fn grant_role(
            &mut self,
            role_id: [u8; 32],
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRole, Self::Env>;
        fn import_positions(
            &mut self,
            positions: Vec<ImportedPosition>,
        ) -> sails_rs::client::PendingCall<io::ImportPositions, Self::Env>;
        fn import_quote_nonces(
            &mut self,
            nonces: Vec<ImportedQuoteNonce>,
        ) -> sails_rs::client::PendingCall<io::ImportQuoteNonces, Self::Env>;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn place_bet(
            &mut self,
            basket_id: u64,
            amount: U256,
            signed_quote: SignedBetQuote,
        ) -> sails_rs::client::PendingCall<io::PlaceBet, Self::Env>;
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env>;
        fn revoke_role(
            &mut self,
            role_id: [u8; 32],
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRole, Self::Env>;
        fn rotate_quote_signer(
            &mut self,
            new_quote_signer: ActorId,
        ) -> sails_rs::client::PendingCall<io::RotateQuoteSigner, Self::Env>;
        fn set_config(
            &mut self,
            config: BetLaneConfig,
        ) -> sails_rs::client::PendingCall<io::SetConfig, Self::Env>;
        fn set_dependencies(
            &mut self,
            dependencies: BetLaneDependencies,
        ) -> sails_rs::client::PendingCall<io::SetDependencies, Self::Env>;
        fn basket_program_id(
            &self,
        ) -> sails_rs::client::PendingCall<io::BasketProgramId, Self::Env>;
        fn bet_token_id(&self) -> sails_rs::client::PendingCall<io::BetTokenId, Self::Env>;
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env>;
        fn get_dependencies(&self)
        -> sails_rs::client::PendingCall<io::GetDependencies, Self::Env>;
        fn get_position(
            &self,
            user: ActorId,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetPosition, Self::Env>;
        fn get_position_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetPositionCount, Self::Env>;
        fn get_positions(
            &self,
            user: ActorId,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env>;
        fn get_used_quote_nonce_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetUsedQuoteNonceCount, Self::Env>;
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env>;
        fn is_quote_nonce_used(
            &self,
            user: ActorId,
            nonce: u128,
        ) -> sails_rs::client::PendingCall<io::IsQuoteNonceUsed, Self::Env>;
        fn quote_signer(&self) -> sails_rs::client::PendingCall<io::QuoteSigner, Self::Env>;
    }
    pub struct BetLaneImpl;
    impl<E: sails_rs::client::GearEnv> BetLane for sails_rs::client::Service<BetLaneImpl, E> {
        type Env = E;
        fn add_admin(
            &mut self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env> {
            self.pending_call((account,))
        }
        fn claim(&mut self, basket_id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn grant_role(
            &mut self,
            role_id: [u8; 32],
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRole, Self::Env> {
            self.pending_call((role_id, account))
        }
        fn import_positions(
            &mut self,
            positions: Vec<ImportedPosition>,
        ) -> sails_rs::client::PendingCall<io::ImportPositions, Self::Env> {
            self.pending_call((positions,))
        }
        fn import_quote_nonces(
            &mut self,
            nonces: Vec<ImportedQuoteNonce>,
        ) -> sails_rs::client::PendingCall<io::ImportQuoteNonces, Self::Env> {
            self.pending_call((nonces,))
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn place_bet(
            &mut self,
            basket_id: u64,
            amount: U256,
            signed_quote: SignedBetQuote,
        ) -> sails_rs::client::PendingCall<io::PlaceBet, Self::Env> {
            self.pending_call((basket_id, amount, signed_quote))
        }
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env> {
            self.pending_call(())
        }
        fn revoke_role(
            &mut self,
            role_id: [u8; 32],
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRole, Self::Env> {
            self.pending_call((role_id, account))
        }
        fn rotate_quote_signer(
            &mut self,
            new_quote_signer: ActorId,
        ) -> sails_rs::client::PendingCall<io::RotateQuoteSigner, Self::Env> {
            self.pending_call((new_quote_signer,))
        }
        fn set_config(
            &mut self,
            config: BetLaneConfig,
        ) -> sails_rs::client::PendingCall<io::SetConfig, Self::Env> {
            self.pending_call((config,))
        }
        fn set_dependencies(
            &mut self,
            dependencies: BetLaneDependencies,
        ) -> sails_rs::client::PendingCall<io::SetDependencies, Self::Env> {
            self.pending_call((dependencies,))
        }
        fn basket_program_id(
            &self,
        ) -> sails_rs::client::PendingCall<io::BasketProgramId, Self::Env> {
            self.pending_call(())
        }
        fn bet_token_id(&self) -> sails_rs::client::PendingCall<io::BetTokenId, Self::Env> {
            self.pending_call(())
        }
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env> {
            self.pending_call(())
        }
        fn get_dependencies(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetDependencies, Self::Env> {
            self.pending_call(())
        }
        fn get_position(
            &self,
            user: ActorId,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetPosition, Self::Env> {
            self.pending_call((user, basket_id))
        }
        fn get_position_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetPositionCount, Self::Env> {
            self.pending_call(())
        }
        fn get_positions(
            &self,
            user: ActorId,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env> {
            self.pending_call((user, offset, limit))
        }
        fn get_used_quote_nonce_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetUsedQuoteNonceCount, Self::Env> {
            self.pending_call(())
        }
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env> {
            self.pending_call(())
        }
        fn is_quote_nonce_used(
            &self,
            user: ActorId,
            nonce: u128,
        ) -> sails_rs::client::PendingCall<io::IsQuoteNonceUsed, Self::Env> {
            self.pending_call((user, nonce))
        }
        fn quote_signer(&self) -> sails_rs::client::PendingCall<io::QuoteSigner, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddAdmin (account: ActorId) -> ());
        sails_rs::io_struct_impl!(Claim (basket_id: u64) -> U256);
        sails_rs::io_struct_impl!(GrantRole (role_id: [u8; 32], account: ActorId) -> ());
        sails_rs::io_struct_impl!(ImportPositions (positions: Vec<super::ImportedPosition>) -> u32);
        sails_rs::io_struct_impl!(ImportQuoteNonces (nonces: Vec<super::ImportedQuoteNonce>) -> u32);
        sails_rs::io_struct_impl!(Pause () -> ());
        sails_rs::io_struct_impl!(PlaceBet (basket_id: u64, amount: U256, signed_quote: super::SignedBetQuote) -> U256);
        sails_rs::io_struct_impl!(Resume () -> ());
        sails_rs::io_struct_impl!(RevokeRole (role_id: [u8; 32], account: ActorId) -> ());
        sails_rs::io_struct_impl!(RotateQuoteSigner (new_quote_signer: ActorId) -> ());
        sails_rs::io_struct_impl!(SetConfig (config: super::BetLaneConfig) -> ());
        sails_rs::io_struct_impl!(SetDependencies (dependencies: super::BetLaneDependencies) -> ());
        sails_rs::io_struct_impl!(BasketProgramId () -> ActorId);
        sails_rs::io_struct_impl!(BetTokenId () -> ActorId);
        sails_rs::io_struct_impl!(GetConfig () -> super::BetLaneConfig);
        sails_rs::io_struct_impl!(GetDependencies () -> super::BetLaneDependencies);
        sails_rs::io_struct_impl!(GetPosition (user: ActorId, basket_id: u64) -> super::Position);
        sails_rs::io_struct_impl!(GetPositionCount () -> u64);
        sails_rs::io_struct_impl!(GetPositions (user: ActorId, offset: u32, limit: u32) -> Result<Vec<super::UserPositionView>, super::BetLaneError>);
        sails_rs::io_struct_impl!(GetUsedQuoteNonceCount () -> u64);
        sails_rs::io_struct_impl!(IsPaused () -> bool);
        sails_rs::io_struct_impl!(IsQuoteNonceUsed (user: ActorId, nonce: u128) -> bool);
        sails_rs::io_struct_impl!(QuoteSigner () -> ActorId);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum BetLaneEvents {
            BetPlaced {
                basket_id: u64,
                user: ActorId,
                amount: U256,
                user_total: U256,
                quoted_index_bps: u16,
                position_index_at_creation_bps: u16,
                quote_nonce: u128,
            },
            Claimed {
                basket_id: u64,
                user: ActorId,
                amount: U256,
            },
            Paused,
            Resumed,
            ConfigUpdated(BetLaneConfig),
            DependenciesUpdated(BetLaneDependencies),
            QuoteSignerRotated {
                previous_quote_signer: ActorId,
                new_quote_signer: ActorId,
            },
            MigrationPositionsImported {
                count: u32,
            },
            MigrationQuoteNoncesImported {
                count: u32,
            },
        }
        impl sails_rs::client::Event for BetLaneEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "BetPlaced",
                "Claimed",
                "Paused",
                "Resumed",
                "ConfigUpdated",
                "DependenciesUpdated",
                "QuoteSignerRotated",
                "MigrationPositionsImported",
                "MigrationQuoteNoncesImported",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for BetLaneImpl {
            type Event = BetLaneEvents;
        }
    }
}

pub mod access_control {
    use super::*;
    pub trait AccessControl {
        type Env: sails_rs::client::GearEnv;
        /// Grants `role_id` to `target_account`.
        ///
        /// If `target_account` had not been already granted `role_id`, emits a `RoleGranted`
        /// event.
        ///
        /// # Requirements
        ///
        /// * The caller must have `role_id`'s admin role.
        fn grant_role(
            &mut self,
            role_id: [u8; 32],
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRole, Self::Env>;
        /// Grants `role_ids` to `target_account`.
        ///
        /// If `target_account` had not been already granted any of the `role_ids`,
        /// emits a `RoleGranted` event for each newly granted role.
        ///
        /// # Requirements
        ///
        /// * The caller must have the admin role for all specified `role_ids`.
        fn grant_roles_batch(
            &mut self,
            role_ids: Vec<[u8; 32]>,
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRolesBatch, Self::Env>;
        /// Revokes `role_id` from the calling account.
        ///
        /// Roles are often managed via `grant_role` and `revoke_role`: this function's
        /// purpose is to provide a mechanism for accounts to lose their privileges
        /// if they are compromised (such as when a trusted device is misplaced).
        ///
        /// If the calling account had been granted `role_id`, emits a `RoleRevoked`
        /// event.
        ///
        /// # Requirements
        ///
        /// * The caller must be `account_id`.
        fn renounce_role(
            &mut self,
            role_id: [u8; 32],
            account_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::RenounceRole, Self::Env>;
        /// Revokes `role_id` from `target_account`.
        ///
        /// If `target_account` had been granted `role_id`, emits a `RoleRevoked` event.
        ///
        /// # Requirements
        ///
        /// * The caller must have `role_id`'s admin role.
        fn revoke_role(
            &mut self,
            role_id: [u8; 32],
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRole, Self::Env>;
        /// Revokes `role_ids` from `target_account`.
        ///
        /// If `target_account` had been granted any of the `role_ids`,
        /// emits a `RoleRevoked` event for each newly revoked role.
        ///
        /// # Requirements
        ///
        /// * The caller must have the admin role for all specified `role_ids`.
        fn revoke_roles_batch(
            &mut self,
            role_ids: Vec<[u8; 32]>,
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRolesBatch, Self::Env>;
        /// Sets `new_admin_role_id` as the admin role for `role_id`.
        ///
        /// Emits a `RoleAdminChanged` event.
        ///
        /// # Requirements
        ///
        /// * The caller must have `role_id`'s admin role.
        fn set_role_admin(
            &mut self,
            role_id: [u8; 32],
            new_admin_role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::SetRoleAdmin, Self::Env>;
        /// Returns the number of roles assigned to the specified member.
        ///
        /// # Arguments
        ///
        /// * `member_id` - The account identifier.
        fn get_member_role_count(
            &self,
            member_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetMemberRoleCount, Self::Env>;
        /// Returns a list of roles assigned to the specified member with pagination.
        ///
        /// # Arguments
        ///
        /// * `member_id` - The account identifier.
        /// * `query` - Optional pagination configuration.
        fn get_member_roles(
            &self,
            member_id: ActorId,
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetMemberRoles, Self::Env>;
        /// Returns the admin role ID that controls `role_id`.
        ///
        /// # Arguments
        ///
        /// * `role_id` - The role identifier.
        ///
        /// # Returns
        ///
        /// The `RoleId` of the administrator.
        fn get_role_admin(
            &self,
            role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::GetRoleAdmin, Self::Env>;
        /// Returns the total number of roles in the system.
        fn get_role_count(&self) -> sails_rs::client::PendingCall<io::GetRoleCount, Self::Env>;
        /// Returns the number of members in the specified role.
        ///
        /// # Arguments
        ///
        /// * `role_id` - The role identifier.
        fn get_role_member_count(
            &self,
            role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::GetRoleMemberCount, Self::Env>;
        /// Returns a list of members in the specified role with pagination.
        ///
        /// # Arguments
        ///
        /// * `role_id` - The role identifier.
        /// * `query` - Optional pagination configuration.
        fn get_role_members(
            &self,
            role_id: [u8; 32],
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetRoleMembers, Self::Env>;
        /// Returns a list of role IDs with pagination.
        ///
        /// # Arguments
        ///
        /// * `query` - Optional pagination configuration.
        fn get_roles(
            &self,
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetRoles, Self::Env>;
        /// Checks if `account_id` has been granted `role_id`.
        ///
        /// # Arguments
        ///
        /// * `role_id` - The role identifier.
        /// * `account_id` - The account identifier.
        ///
        /// # Returns
        ///
        /// `true` if the account possesses the role.
        fn has_role(
            &self,
            role_id: [u8; 32],
            account_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::HasRole, Self::Env>;
    }
    pub struct AccessControlImpl;
    impl<E: sails_rs::client::GearEnv> AccessControl
        for sails_rs::client::Service<AccessControlImpl, E>
    {
        type Env = E;
        fn grant_role(
            &mut self,
            role_id: [u8; 32],
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRole, Self::Env> {
            self.pending_call((role_id, target_account))
        }
        fn grant_roles_batch(
            &mut self,
            role_ids: Vec<[u8; 32]>,
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantRolesBatch, Self::Env> {
            self.pending_call((role_ids, target_account))
        }
        fn renounce_role(
            &mut self,
            role_id: [u8; 32],
            account_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::RenounceRole, Self::Env> {
            self.pending_call((role_id, account_id))
        }
        fn revoke_role(
            &mut self,
            role_id: [u8; 32],
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRole, Self::Env> {
            self.pending_call((role_id, target_account))
        }
        fn revoke_roles_batch(
            &mut self,
            role_ids: Vec<[u8; 32]>,
            target_account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeRolesBatch, Self::Env> {
            self.pending_call((role_ids, target_account))
        }
        fn set_role_admin(
            &mut self,
            role_id: [u8; 32],
            new_admin_role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::SetRoleAdmin, Self::Env> {
            self.pending_call((role_id, new_admin_role_id))
        }
        fn get_member_role_count(
            &self,
            member_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetMemberRoleCount, Self::Env> {
            self.pending_call((member_id,))
        }
        fn get_member_roles(
            &self,
            member_id: ActorId,
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetMemberRoles, Self::Env> {
            self.pending_call((member_id, query))
        }
        fn get_role_admin(
            &self,
            role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::GetRoleAdmin, Self::Env> {
            self.pending_call((role_id,))
        }
        fn get_role_count(&self) -> sails_rs::client::PendingCall<io::GetRoleCount, Self::Env> {
            self.pending_call(())
        }
        fn get_role_member_count(
            &self,
            role_id: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::GetRoleMemberCount, Self::Env> {
            self.pending_call((role_id,))
        }
        fn get_role_members(
            &self,
            role_id: [u8; 32],
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetRoleMembers, Self::Env> {
            self.pending_call((role_id, query))
        }
        fn get_roles(
            &self,
            query: Option<Pagination>,
        ) -> sails_rs::client::PendingCall<io::GetRoles, Self::Env> {
            self.pending_call((query,))
        }
        fn has_role(
            &self,
            role_id: [u8; 32],
            account_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::HasRole, Self::Env> {
            self.pending_call((role_id, account_id))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(GrantRole (role_id: [u8; 32], target_account: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantRolesBatch (role_ids: Vec<[u8; 32]>, target_account: ActorId) -> ());
        sails_rs::io_struct_impl!(RenounceRole (role_id: [u8; 32], account_id: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeRole (role_id: [u8; 32], target_account: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeRolesBatch (role_ids: Vec<[u8; 32]>, target_account: ActorId) -> ());
        sails_rs::io_struct_impl!(SetRoleAdmin (role_id: [u8; 32], new_admin_role_id: [u8; 32]) -> ());
        sails_rs::io_struct_impl!(GetMemberRoleCount (member_id: ActorId) -> u32);
        sails_rs::io_struct_impl!(GetMemberRoles (member_id: ActorId, query: Option<super::Pagination>) -> Vec<[u8; 32]>);
        sails_rs::io_struct_impl!(GetRoleAdmin (role_id: [u8; 32]) -> [u8; 32]);
        sails_rs::io_struct_impl!(GetRoleCount () -> u32);
        sails_rs::io_struct_impl!(GetRoleMemberCount (role_id: [u8; 32]) -> u32);
        sails_rs::io_struct_impl!(GetRoleMembers (role_id: [u8; 32], query: Option<super::Pagination>) -> Vec<ActorId>);
        sails_rs::io_struct_impl!(GetRoles (query: Option<super::Pagination>) -> Vec<[u8; 32]>);
        sails_rs::io_struct_impl!(HasRole (role_id: [u8; 32], account_id: ActorId) -> bool);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum AccessControlEvents {
            /// Emitted when `target_account` is granted `role_id`.
            RoleGranted {
                role_id: [u8; 32],
                target_account: ActorId,
                sender: ActorId,
            },
            /// Emitted when `role_id` is revoked from `target_account`.
            RoleRevoked {
                role_id: [u8; 32],
                target_account: ActorId,
                sender: ActorId,
            },
            /// Emitted when `new_admin_role_id` is set as the admin role for `role_id`.
            RoleAdminChanged {
                role_id: [u8; 32],
                previous_admin_role_id: [u8; 32],
                new_admin_role_id: [u8; 32],
                sender: ActorId,
            },
        }
        impl sails_rs::client::Event for AccessControlEvents {
            const EVENT_NAMES: &'static [Route] =
                &["RoleGranted", "RoleRevoked", "RoleAdminChanged"];
        }
        impl sails_rs::client::ServiceWithEvents for AccessControlImpl {
            type Event = AccessControlEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct BetLaneConfig {
    pub min_bet: U256,
    pub max_bet: U256,
    pub payouts_allowed_while_paused: bool,
    pub quote_signer: ActorId,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ImportedPosition {
    pub basket_id: u64,
    pub user: ActorId,
    pub shares: U256,
    pub claimed: bool,
    pub index_at_creation_bps: u16,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ImportedQuoteNonce {
    pub user: ActorId,
    pub nonce: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SignedBetQuote {
    pub payload: BetQuotePayload,
    pub signature: Vec<u8>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct BetQuotePayload {
    pub target_program_id: ActorId,
    pub user: ActorId,
    pub basket_id: u64,
    pub amount: U256,
    pub quoted_index_bps: u16,
    pub deadline_ms: u64,
    pub nonce: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct BetLaneDependencies {
    pub basket_program_id: ActorId,
    pub bet_token_id: ActorId,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Position {
    pub shares: U256,
    pub claimed: bool,
    pub index_at_creation_bps: u16,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct UserPositionView {
    pub basket_id: u64,
    pub position: Position,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum BetLaneError {
    AccessDenied,
    Paused,
    InvalidConfig,
    InvalidAmount,
    AmountBelowMinBet,
    AmountAboveMaxBet,
    InvalidIndexAtCreation,
    QuoteSignerNotConfigured,
    QuoteTargetMismatch,
    QuoteUserMismatch,
    QuoteBasketMismatch,
    QuoteAmountMismatch,
    QuoteExpired,
    QuoteNonceAlreadyUsed,
    InvalidQuoteSignature,
    InvalidQuoteSigner,
    QuoteVerificationFailed,
    BasketQueryFailed,
    BasketNotFound,
    BasketNotActive,
    BasketAssetMismatch,
    SettlementQueryFailed,
    SettlementNotFound,
    SettlementNotFinalized,
    NothingToClaim,
    AlreadyClaimed,
    OperationInProgress,
    BetTokenTransferFromFailed,
    BetTokenPayoutFailed,
    BetTokenRefundFailed,
    MathOverflow,
    InvalidPageSize,
    EventEmitFailed,
    RoleManagementFailed,
    MigrationRequiresPause,
    MigrationBatchTooLarge,
}
/// Pagination parameters for listing roles or members.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Pagination {
    /// The number of items to skip.
    pub offset: u32,
    /// The maximum number of items to return.
    pub limit: u32,
}
