[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
polybaskets_escrow = "5mzLoAijdzAQV5D7QXe6TTGZ9TkWQanygfnb5VPPxFSm"

[programs.devnet]
polybaskets_escrow = "5mzLoAijdzAQV5D7QXe6TTGZ9TkWQanygfnb5VPPxFSm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_OPTIONS='--import tsx' npx mocha -t 1000000 'tests/**/*.ts'"
