// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct FreebetLedgerProgram;
impl sails_rs::client::Program for FreebetLedgerProgram {}
pub trait FreebetLedger {
    type Env: sails_rs::client::GearEnv;
    fn freebet_ledger(
        &self,
    ) -> sails_rs::client::Service<freebet_ledger::FreebetLedgerImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> FreebetLedger
    for sails_rs::client::Actor<FreebetLedgerProgram, E>
{
    type Env = E;
    fn freebet_ledger(
        &self,
    ) -> sails_rs::client::Service<freebet_ledger::FreebetLedgerImpl, Self::Env> {
        self.service(stringify!(FreebetLedger))
    }
}
pub trait FreebetLedgerCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        init: FreebetLedgerInit,
    ) -> sails_rs::client::PendingCtor<FreebetLedgerProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> FreebetLedgerCtors
    for sails_rs::client::Deployment<FreebetLedgerProgram, E>
{
    type Env = E;
    fn new(
        self,
        init: FreebetLedgerInit,
    ) -> sails_rs::client::PendingCtor<FreebetLedgerProgram, io::New, Self::Env> {
        self.pending_ctor((init,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (init: super::FreebetLedgerInit) -> ());
}

pub mod freebet_ledger {
    use super::*;
    pub trait FreebetLedger {
        type Env: sails_rs::client::GearEnv;
        fn authorize_bet_program(
            &mut self,
            program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::AuthorizeBetProgram, Self::Env>;
        fn grant(
            &mut self,
            to: ActorId,
            grant_id: String,
            reason: String,
        ) -> sails_rs::client::PendingCall<io::Grant, Self::Env>;
        fn return_freebet(
            &mut self,
            user: ActorId,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::ReturnFreebet, Self::Env>;
        fn revoke_bet_program(
            &mut self,
            program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeBetProgram, Self::Env>;
        fn spend_freebet(
            &mut self,
            bet_program_id: ActorId,
            basket_id: u64,
            amount: u128,
            signed_quote: SignedVaraBetQuote,
        ) -> sails_rs::client::PendingCall<io::SpendFreebet, Self::Env>;
        fn admin(&self) -> sails_rs::client::PendingCall<io::Admin, Self::Env>;
        fn balance_of(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        fn get_grant(
            &self,
            grant_id: String,
        ) -> sails_rs::client::PendingCall<io::GetGrant, Self::Env>;
        fn get_pending_spend_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetPendingSpendCount, Self::Env>;
        fn is_bet_program_authorized(
            &self,
            program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsBetProgramAuthorized, Self::Env>;
    }
    pub struct FreebetLedgerImpl;
    impl<E: sails_rs::client::GearEnv> FreebetLedger
        for sails_rs::client::Service<FreebetLedgerImpl, E>
    {
        type Env = E;
        fn authorize_bet_program(
            &mut self,
            program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::AuthorizeBetProgram, Self::Env> {
            self.pending_call((program_id,))
        }
        fn grant(
            &mut self,
            to: ActorId,
            grant_id: String,
            reason: String,
        ) -> sails_rs::client::PendingCall<io::Grant, Self::Env> {
            self.pending_call((to, grant_id, reason))
        }
        fn return_freebet(
            &mut self,
            user: ActorId,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::ReturnFreebet, Self::Env> {
            self.pending_call((user, basket_id))
        }
        fn revoke_bet_program(
            &mut self,
            program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeBetProgram, Self::Env> {
            self.pending_call((program_id,))
        }
        fn spend_freebet(
            &mut self,
            bet_program_id: ActorId,
            basket_id: u64,
            amount: u128,
            signed_quote: SignedVaraBetQuote,
        ) -> sails_rs::client::PendingCall<io::SpendFreebet, Self::Env> {
            self.pending_call((bet_program_id, basket_id, amount, signed_quote))
        }
        fn admin(&self) -> sails_rs::client::PendingCall<io::Admin, Self::Env> {
            self.pending_call(())
        }
        fn balance_of(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((user,))
        }
        fn get_grant(
            &self,
            grant_id: String,
        ) -> sails_rs::client::PendingCall<io::GetGrant, Self::Env> {
            self.pending_call((grant_id,))
        }
        fn get_pending_spend_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetPendingSpendCount, Self::Env> {
            self.pending_call(())
        }
        fn is_bet_program_authorized(
            &self,
            program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsBetProgramAuthorized, Self::Env> {
            self.pending_call((program_id,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AuthorizeBetProgram (program_id: ActorId) -> ());
        sails_rs::io_struct_impl!(Grant (to: ActorId, grant_id: String, reason: String) -> u128);
        sails_rs::io_struct_impl!(ReturnFreebet (user: ActorId, basket_id: u64) -> u128);
        sails_rs::io_struct_impl!(RevokeBetProgram (program_id: ActorId) -> ());
        sails_rs::io_struct_impl!(SpendFreebet (bet_program_id: ActorId, basket_id: u64, amount: u128, signed_quote: super::SignedVaraBetQuote) -> u128);
        sails_rs::io_struct_impl!(Admin () -> ActorId);
        sails_rs::io_struct_impl!(BalanceOf (user: ActorId) -> u128);
        sails_rs::io_struct_impl!(GetGrant (grant_id: String) -> Option<super::FreebetGrant>);
        sails_rs::io_struct_impl!(GetPendingSpendCount () -> u64);
        sails_rs::io_struct_impl!(IsBetProgramAuthorized (program_id: ActorId) -> bool);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum FreebetLedgerEvents {
            BetProgramAuthorized {
                program_id: ActorId,
            },
            BetProgramRevoked {
                program_id: ActorId,
            },
            FreebetGranted {
                recipient: ActorId,
                amount: u128,
                balance: u128,
                grant_id: String,
                reason: String,
            },
            FreebetSpent {
                user: ActorId,
                bet_program_id: ActorId,
                basket_id: u64,
                amount: u128,
                remaining_balance: u128,
            },
            FreebetReturned {
                user: ActorId,
                bet_program_id: ActorId,
                basket_id: u64,
                amount: u128,
                balance: u128,
            },
            FreebetSpendFailed {
                user: ActorId,
                bet_program_id: ActorId,
                basket_id: u64,
                amount: u128,
                restored_balance: u128,
            },
        }
        impl sails_rs::client::Event for FreebetLedgerEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "BetProgramAuthorized",
                "BetProgramRevoked",
                "FreebetGranted",
                "FreebetSpent",
                "FreebetReturned",
                "FreebetSpendFailed",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for FreebetLedgerImpl {
            type Event = FreebetLedgerEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct FreebetLedgerInit {
    pub admin: ActorId,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SignedVaraBetQuote {
    pub payload: VaraBetQuotePayload,
    pub signature: Vec<u8>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct VaraBetQuotePayload {
    pub target_program_id: ActorId,
    pub user: ActorId,
    pub basket_id: u64,
    pub amount: u128,
    pub quoted_index_bps: u16,
    pub earliest_end_timestamp: u64,
    pub deadline_ms: u64,
    pub nonce: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct FreebetGrant {
    pub id: String,
    pub recipient: ActorId,
    pub amount: u128,
    pub reason: String,
    pub granted_at: u64,
}
