// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct PolymarketMirrorProgram;
impl sails_rs::client::Program for PolymarketMirrorProgram {}
pub trait PolymarketMirror {
    type Env: sails_rs::client::GearEnv;
    fn basket_market(
        &self,
    ) -> sails_rs::client::Service<basket_market::BasketMarketImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> PolymarketMirror
    for sails_rs::client::Actor<PolymarketMirrorProgram, E>
{
    type Env = E;
    fn basket_market(
        &self,
    ) -> sails_rs::client::Service<basket_market::BasketMarketImpl, Self::Env> {
        self.service(stringify!(BasketMarket))
    }
}
pub trait PolymarketMirrorCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        init: BasketMarketInit,
    ) -> sails_rs::client::PendingCtor<PolymarketMirrorProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> PolymarketMirrorCtors
    for sails_rs::client::Deployment<PolymarketMirrorProgram, E>
{
    type Env = E;
    fn new(
        self,
        init: BasketMarketInit,
    ) -> sails_rs::client::PendingCtor<PolymarketMirrorProgram, io::New, Self::Env> {
        self.pending_ctor((init,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (init: super::BasketMarketInit) -> ());
}

pub mod basket_market {
    use super::*;
    pub trait BasketMarket {
        type Env: sails_rs::client::GearEnv;
        fn admin_withdraw_vara(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::AdminWithdrawVara, Self::Env>;
        fn bet_on_basket(
            &mut self,
            basket_id: u64,
            signed_quote: SignedVaraBetQuote,
        ) -> sails_rs::client::PendingCall<io::BetOnBasket, Self::Env>;
        fn bet_on_basket_from_freebet_ledger(
            &mut self,
            user: ActorId,
            basket_id: u64,
            signed_quote: SignedVaraBetQuote,
        ) -> sails_rs::client::PendingCall<io::BetOnBasketFromFreebetLedger, Self::Env>;
        fn claim(&mut self, basket_id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env>;
        fn create_basket(
            &mut self,
            name: String,
            description: String,
            items: Vec<BasketItem>,
            asset_kind: BasketAssetKind,
        ) -> sails_rs::client::PendingCall<io::CreateBasket, Self::Env>;
        fn finalize_settlement(
            &mut self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeSettlement, Self::Env>;
        fn import_agents(
            &mut self,
            agents: Vec<AgentInfo>,
        ) -> sails_rs::client::PendingCall<io::ImportAgents, Self::Env>;
        fn import_baskets(
            &mut self,
            baskets: Vec<Basket>,
        ) -> sails_rs::client::PendingCall<io::ImportBaskets, Self::Env>;
        fn import_positions(
            &mut self,
            positions: Vec<Position>,
        ) -> sails_rs::client::PendingCall<io::ImportPositions, Self::Env>;
        fn import_settlements(
            &mut self,
            settlements: Vec<Settlement>,
        ) -> sails_rs::client::PendingCall<io::ImportSettlements, Self::Env>;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn propose_settlement(
            &mut self,
            basket_id: u64,
            item_resolutions: Vec<ItemResolution>,
            payload: String,
        ) -> sails_rs::client::PendingCall<io::ProposeSettlement, Self::Env>;
        /// Register an agent with a display name, or rename if already registered.
        /// Input is normalized to lowercase. Names must be 3-20 chars, alphanumeric
        /// and hyphens only, no leading/trailing hyphens. Rename has a 7-day cooldown.
        fn register_agent(
            &mut self,
            name: String,
        ) -> sails_rs::client::PendingCall<io::RegisterAgent, Self::Env>;
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env>;
        fn set_config(
            &mut self,
            config: BasketMarketConfig,
        ) -> sails_rs::client::PendingCall<io::SetConfig, Self::Env>;
        fn set_freebet_ledger(
            &mut self,
            ledger_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetFreebetLedger, Self::Env>;
        fn set_vara_enabled(
            &mut self,
            enabled: bool,
        ) -> sails_rs::client::PendingCall<io::SetVaraEnabled, Self::Env>;
        fn get_agent(
            &self,
            address: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAgent, Self::Env>;
        fn get_agent_count(&self) -> sails_rs::client::PendingCall<io::GetAgentCount, Self::Env>;
        fn get_all_agents(&self) -> sails_rs::client::PendingCall<io::GetAllAgents, Self::Env>;
        fn get_basket(
            &self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetBasket, Self::Env>;
        fn get_basket_count(&self) -> sails_rs::client::PendingCall<io::GetBasketCount, Self::Env>;
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env>;
        fn get_freebet_ledger(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetFreebetLedger, Self::Env>;
        fn get_freebet_positions(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetFreebetPositions, Self::Env>;
        fn get_positions(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env>;
        fn get_settlement(
            &self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetSettlement, Self::Env>;
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env>;
        fn is_vara_enabled(&self) -> sails_rs::client::PendingCall<io::IsVaraEnabled, Self::Env>;
    }
    pub struct BasketMarketImpl;
    impl<E: sails_rs::client::GearEnv> BasketMarket for sails_rs::client::Service<BasketMarketImpl, E> {
        type Env = E;
        fn admin_withdraw_vara(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::AdminWithdrawVara, Self::Env> {
            self.pending_call((to, amount))
        }
        fn bet_on_basket(
            &mut self,
            basket_id: u64,
            signed_quote: SignedVaraBetQuote,
        ) -> sails_rs::client::PendingCall<io::BetOnBasket, Self::Env> {
            self.pending_call((basket_id, signed_quote))
        }
        fn bet_on_basket_from_freebet_ledger(
            &mut self,
            user: ActorId,
            basket_id: u64,
            signed_quote: SignedVaraBetQuote,
        ) -> sails_rs::client::PendingCall<io::BetOnBasketFromFreebetLedger, Self::Env> {
            self.pending_call((user, basket_id, signed_quote))
        }
        fn claim(&mut self, basket_id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn create_basket(
            &mut self,
            name: String,
            description: String,
            items: Vec<BasketItem>,
            asset_kind: BasketAssetKind,
        ) -> sails_rs::client::PendingCall<io::CreateBasket, Self::Env> {
            self.pending_call((name, description, items, asset_kind))
        }
        fn finalize_settlement(
            &mut self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeSettlement, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn import_agents(
            &mut self,
            agents: Vec<AgentInfo>,
        ) -> sails_rs::client::PendingCall<io::ImportAgents, Self::Env> {
            self.pending_call((agents,))
        }
        fn import_baskets(
            &mut self,
            baskets: Vec<Basket>,
        ) -> sails_rs::client::PendingCall<io::ImportBaskets, Self::Env> {
            self.pending_call((baskets,))
        }
        fn import_positions(
            &mut self,
            positions: Vec<Position>,
        ) -> sails_rs::client::PendingCall<io::ImportPositions, Self::Env> {
            self.pending_call((positions,))
        }
        fn import_settlements(
            &mut self,
            settlements: Vec<Settlement>,
        ) -> sails_rs::client::PendingCall<io::ImportSettlements, Self::Env> {
            self.pending_call((settlements,))
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn propose_settlement(
            &mut self,
            basket_id: u64,
            item_resolutions: Vec<ItemResolution>,
            payload: String,
        ) -> sails_rs::client::PendingCall<io::ProposeSettlement, Self::Env> {
            self.pending_call((basket_id, item_resolutions, payload))
        }
        fn register_agent(
            &mut self,
            name: String,
        ) -> sails_rs::client::PendingCall<io::RegisterAgent, Self::Env> {
            self.pending_call((name,))
        }
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env> {
            self.pending_call(())
        }
        fn set_config(
            &mut self,
            config: BasketMarketConfig,
        ) -> sails_rs::client::PendingCall<io::SetConfig, Self::Env> {
            self.pending_call((config,))
        }
        fn set_freebet_ledger(
            &mut self,
            ledger_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetFreebetLedger, Self::Env> {
            self.pending_call((ledger_id,))
        }
        fn set_vara_enabled(
            &mut self,
            enabled: bool,
        ) -> sails_rs::client::PendingCall<io::SetVaraEnabled, Self::Env> {
            self.pending_call((enabled,))
        }
        fn get_agent(
            &self,
            address: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetAgent, Self::Env> {
            self.pending_call((address,))
        }
        fn get_agent_count(&self) -> sails_rs::client::PendingCall<io::GetAgentCount, Self::Env> {
            self.pending_call(())
        }
        fn get_all_agents(&self) -> sails_rs::client::PendingCall<io::GetAllAgents, Self::Env> {
            self.pending_call(())
        }
        fn get_basket(
            &self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetBasket, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn get_basket_count(&self) -> sails_rs::client::PendingCall<io::GetBasketCount, Self::Env> {
            self.pending_call(())
        }
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env> {
            self.pending_call(())
        }
        fn get_freebet_ledger(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetFreebetLedger, Self::Env> {
            self.pending_call(())
        }
        fn get_freebet_positions(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetFreebetPositions, Self::Env> {
            self.pending_call((user,))
        }
        fn get_positions(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env> {
            self.pending_call((user,))
        }
        fn get_settlement(
            &self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetSettlement, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env> {
            self.pending_call(())
        }
        fn is_vara_enabled(&self) -> sails_rs::client::PendingCall<io::IsVaraEnabled, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AdminWithdrawVara (to: ActorId, amount: u128) -> u128);
        sails_rs::io_struct_impl!(BetOnBasket (basket_id: u64, signed_quote: super::SignedVaraBetQuote) -> u128);
        sails_rs::io_struct_impl!(BetOnBasketFromFreebetLedger (user: ActorId, basket_id: u64, signed_quote: super::SignedVaraBetQuote) -> u128);
        sails_rs::io_struct_impl!(Claim (basket_id: u64) -> u128);
        sails_rs::io_struct_impl!(CreateBasket (name: String, description: String, items: Vec<super::BasketItem>, asset_kind: super::BasketAssetKind) -> u64);
        sails_rs::io_struct_impl!(FinalizeSettlement (basket_id: u64) -> ());
        sails_rs::io_struct_impl!(ImportAgents (agents: Vec<super::AgentInfo>) -> u32);
        sails_rs::io_struct_impl!(ImportBaskets (baskets: Vec<super::Basket>) -> u32);
        sails_rs::io_struct_impl!(ImportPositions (positions: Vec<super::Position>) -> u32);
        sails_rs::io_struct_impl!(ImportSettlements (settlements: Vec<super::Settlement>) -> u32);
        sails_rs::io_struct_impl!(Pause () -> ());
        sails_rs::io_struct_impl!(ProposeSettlement (basket_id: u64, item_resolutions: Vec<super::ItemResolution>, payload: String) -> ());
        sails_rs::io_struct_impl!(RegisterAgent (name: String) -> ());
        sails_rs::io_struct_impl!(Resume () -> ());
        sails_rs::io_struct_impl!(SetConfig (config: super::BasketMarketConfig) -> ());
        sails_rs::io_struct_impl!(SetFreebetLedger (ledger_id: ActorId) -> ());
        sails_rs::io_struct_impl!(SetVaraEnabled (enabled: bool) -> ());
        sails_rs::io_struct_impl!(GetAgent (address: ActorId) -> Option<super::AgentInfo>);
        sails_rs::io_struct_impl!(GetAgentCount () -> u64);
        sails_rs::io_struct_impl!(GetAllAgents () -> Vec<super::AgentInfo>);
        sails_rs::io_struct_impl!(GetBasket (basket_id: u64) -> Result<super::Basket, super::BasketMarketError>);
        sails_rs::io_struct_impl!(GetBasketCount () -> u64);
        sails_rs::io_struct_impl!(GetConfig () -> super::BasketMarketConfig);
        sails_rs::io_struct_impl!(GetFreebetLedger () -> ActorId);
        sails_rs::io_struct_impl!(GetFreebetPositions (user: ActorId) -> Vec<super::Position>);
        sails_rs::io_struct_impl!(GetPositions (user: ActorId) -> Vec<super::Position>);
        sails_rs::io_struct_impl!(GetSettlement (basket_id: u64) -> Result<super::Settlement, super::BasketMarketError>);
        sails_rs::io_struct_impl!(IsPaused () -> bool);
        sails_rs::io_struct_impl!(IsVaraEnabled () -> bool);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum BasketMarketEvents {
            BasketCreated {
                basket_id: u64,
                creator: ActorId,
                asset_kind: BasketAssetKind,
            },
            VaraBetPlaced {
                basket_id: u64,
                user: ActorId,
                amount: u128,
                user_total: u128,
                index_at_creation_bps: u16,
                quote_nonce: u128,
            },
            FreebetBetPlaced {
                basket_id: u64,
                user: ActorId,
                amount: u128,
                user_total: u128,
                index_at_creation_bps: u16,
                quote_nonce: u128,
            },
            SettlementProposed {
                basket_id: u64,
                asset_kind: BasketAssetKind,
                proposer: ActorId,
                payout_per_share: u128,
                challenge_deadline: u64,
            },
            SettlementFinalized {
                basket_id: u64,
                asset_kind: BasketAssetKind,
                finalized_at: u64,
                payout_per_share: u128,
            },
            Claimed {
                basket_id: u64,
                user: ActorId,
                amount: u128,
            },
            AdminVaraWithdrawn {
                to: ActorId,
                amount: u128,
            },
            AgentRegistered {
                agent: ActorId,
                name: String,
            },
            AgentRenamed {
                agent: ActorId,
                old_name: String,
                new_name: String,
            },
            VaraSupportUpdated {
                enabled: bool,
            },
            ConfigUpdated {
                config: BasketMarketConfig,
            },
            Paused,
            Resumed,
            MigrationBatchImported {
                entity: MigrationEntityKind,
                count: u32,
            },
        }
        impl sails_rs::client::Event for BasketMarketEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "BasketCreated",
                "VaraBetPlaced",
                "FreebetBetPlaced",
                "SettlementProposed",
                "SettlementFinalized",
                "Claimed",
                "AdminVaraWithdrawn",
                "AgentRegistered",
                "AgentRenamed",
                "VaraSupportUpdated",
                "ConfigUpdated",
                "Paused",
                "Resumed",
                "MigrationBatchImported",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for BasketMarketImpl {
            type Event = BasketMarketEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct BasketMarketInit {
    pub admin_role: ActorId,
    pub settler_role: ActorId,
    pub liveness_ms: u64,
    pub quote_signer: ActorId,
    pub bet_cutoff_ms: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SignedVaraBetQuote {
    pub payload: VaraBetQuotePayload,
    pub signature: Vec<u8>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct VaraBetQuotePayload {
    pub target_program_id: ActorId,
    pub user: ActorId,
    pub basket_id: u64,
    pub amount: u128,
    pub quoted_index_bps: u16,
    pub earliest_end_timestamp: u64,
    pub deadline_ms: u64,
    pub nonce: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct BasketItem {
    pub poly_market_id: String,
    pub poly_slug: String,
    pub weight_bps: u16,
    pub selected_outcome: Outcome,
    pub end_timestamp: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Outcome {
    YES,
    NO,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum BasketAssetKind {
    Vara,
    Bet,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AgentInfo {
    pub address: ActorId,
    pub name: String,
    pub registered_at: u64,
    pub name_updated_at: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Basket {
    pub id: u64,
    pub creator: ActorId,
    pub name: String,
    pub description: String,
    pub items: Vec<BasketItem>,
    pub created_at: u64,
    pub status: BasketStatus,
    pub asset_kind: BasketAssetKind,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum BasketStatus {
    Active,
    SettlementPending,
    Settled,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Position {
    pub basket_id: u64,
    pub user: ActorId,
    pub shares: u128,
    pub claimed: bool,
    pub index_at_creation_bps: u16,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Settlement {
    pub basket_id: u64,
    pub proposer: ActorId,
    pub item_resolutions: Vec<ItemResolution>,
    pub payout_per_share: u128,
    pub payload: String,
    pub proposed_at: u64,
    pub challenge_deadline: u64,
    pub finalized_at: Option<u64>,
    pub status: SettlementStatus,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ItemResolution {
    pub item_index: u8,
    pub resolved: Outcome,
    pub poly_slug: String,
    pub poly_condition_id: Option<String>,
    pub poly_price_yes: u16,
    pub poly_price_no: u16,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum SettlementStatus {
    Proposed,
    Finalized,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct BasketMarketConfig {
    pub admin_role: ActorId,
    pub settler_role: ActorId,
    pub liveness_ms: u64,
    pub vara_enabled: bool,
    pub min_items_per_basket: u32,
    pub quote_signer: ActorId,
    pub bet_cutoff_ms: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum BasketMarketError {
    Unauthorized,
    Paused,
    MigrationRequiresPause,
    MigrationBatchTooLarge,
    BasketNotFound,
    BasketNotActive,
    BasketAssetMismatch,
    NoItems,
    NotEnoughItems,
    InvalidWeights,
    DuplicateBasketItem,
    TooManyItems,
    NameTooLong,
    DescriptionTooLong,
    MarketIdTooLong,
    SlugTooLong,
    PayloadTooLong,
    VaraDisabled,
    SettlementAlreadyExists,
    SettlementNotFound,
    SettlementNotProposed,
    SettlementNotFinalized,
    ChallengeDeadlineNotPassed,
    InvalidIndexAtCreation,
    QuoteSignerNotConfigured,
    QuoteTargetMismatch,
    QuoteUserMismatch,
    QuoteBasketMismatch,
    QuoteAmountMismatch,
    QuoteExpired,
    QuoteNonceAlreadyUsed,
    InvalidQuoteSignature,
    InvalidQuoteSigner,
    QuoteVerificationFailed,
    BetCutoffReached,
    QuoteExpiryMismatch,
    InvalidBetAmount,
    InvalidFreebetAmount,
    InvalidResolutionCount,
    DuplicateResolutionIndex,
    ResolutionIndexOutOfBounds,
    ResolutionSlugMismatch,
    InvalidResolution,
    AlreadyClaimed,
    NothingToClaim,
    TransferFailed,
    FreebetLedgerNotConfigured,
    FreebetLedgerReturnFailed,
    MathOverflow,
    EventEmitFailed,
    InvalidConfig,
    AgentNameTooShort,
    AgentNameTooLong,
    AgentNameInvalid,
    AgentNameTaken,
    AgentRenameCooldown,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum MigrationEntityKind {
    Baskets,
    Settlements,
    Positions,
    Agents,
}
